ALTER TABLE `Task`
  MODIFY `status` ENUM('NEW', 'IN_PROGRESS', 'AWAITING_INSPECTION', 'DONE', 'BLOCKED') NOT NULL DEFAULT 'NEW';

UPDATE `Task`
SET `status` = 'IN_PROGRESS'
WHERE `status` = 'BLOCKED';

ALTER TABLE `Task`
  DROP COLUMN `deadline`,
  ADD COLUMN `storyPoints` INTEGER NULL,
  MODIFY `status` ENUM('NEW', 'IN_PROGRESS', 'AWAITING_INSPECTION', 'DONE') NOT NULL DEFAULT 'NEW';
